import { jsPDF } from 'jspdf';

export interface ReportInput {
  address: string;
  coordinates: { lat: number; lng: number };
  scores: {
    overall: number;
    services: number;
    mobility: number;
    safety: number;
    environment: number;
  };
  facilityCounts: {
    health: number;
    education: number;
    market: number;
    transport: number;
    walkability: number;
    recreation: number;
    safety: number;
    accessibility: number;
    police: number;
    religious: number;
  };
  nearbyFacilities?: string[];
  aiSummary?: string;
  language?: string;
}

export function generatePdfReport(data: ReportInput) {
  const doc = new jsPDF();

  const marginLeft = 14;
  let cursorY = 18;

  const addHeading = (text: string, size = 16) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(size);
    doc.text(text, marginLeft, cursorY);
    cursorY += 8;
  };

  const addText = (text: string, size = 11) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(size);
    const split = doc.splitTextToSize(text, 180);
    doc.text(split, marginLeft, cursorY);
    cursorY += split.length * 6;
  };

  const addKeyValue = (key: string, value: string | number) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`${key}:`, marginLeft, cursorY);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), marginLeft + 30, cursorY);
    cursorY += 6;
  };

  // Title
  addHeading('Futuricity Location Report');

  // Context
  addText(`Generated: ${new Date().toLocaleString()}`);
  addText(`Language: ${data.language || 'en'}`);

  // Location
  addHeading('Location', 14);
  addKeyValue('Address', data.address);
  addKeyValue('Latitude', data.coordinates.lat.toFixed(6));
  addKeyValue('Longitude', data.coordinates.lng.toFixed(6));

  // Scores
  addHeading('Livability Scores', 14);
  addKeyValue('Overall', Math.round(data.scores.overall));
  addKeyValue('Services', Math.round(data.scores.services));
  addKeyValue('Mobility', Math.round(data.scores.mobility));
  addKeyValue('Safety', Math.round(data.scores.safety));
  addKeyValue('Environment', Math.round(data.scores.environment));

  // Facility counts
  addHeading('Facility Counts', 14);
  Object.entries(data.facilityCounts).forEach(([k, v]) => addKeyValue(k, v as number));

  // AI Summary
  if (data.aiSummary) {
    addHeading('AI Summary', 14);
    addText(data.aiSummary);
  }

  // Nearby facilities
  if (data.nearbyFacilities && data.nearbyFacilities.length > 0) {
    addHeading('Nearby Facilities', 14);
    data.nearbyFacilities.slice(0, 12).forEach((f) => addText(`• ${f}`));
  }

  // Footer
  if (cursorY > 270) {
    doc.addPage();
    cursorY = 18;
  }
  doc.setFontSize(9);
  doc.text('Generated by Futuricity', marginLeft, 285);

  doc.save(`Futuricity_Report_${data.address.replace(/[^a-z0-9]+/gi, '_').slice(0, 40)}.pdf`);
}


